[package]
name = "jock"
version = "1.0.0"
edition = "2021"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
indicatif = "0.17.8"

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
codegen-units = 1
